### ISSUE TITLE
As an admin, I can specify the start time & date when uploading a meeting via CSV

### ISSUE THREAD

**Issue by cfsjsharedadmin** [codeforsanjose/project-happening-atm#175]
As an admin, I can specify the start time & date when uploading a meeting via CSV

**Comment by cfsjsharedadmin** [comment]
Requirements:
- Modify the template CSV file.
- Test the backend API to make sure it handles when a start time & date is not specified - we should return an error
- Persist the start time & date to the database with the rest of the meeting contents from the CSV file.

**Comment by TimothyLe** [comment]
What is the format for the time and date? Is it similar to the `date` command in shell?
E.g. "%m-%d-%y" 
E.g. "hh:mm:ss"
Would the time go by 12-hour clock or 24-hour clock?

**Comment by feliciafalafelc** [comment]
We use time stamps to milliseconds when creating meetings; @TimothyLe @anna-kartynnik

**Comment by anna-kartynnik** [comment]
@TimothyLe right now we use a string that represents the number of milliseconds from 1 Jan 1970, like 

    ... "meeting_start_timestamp": "1618235200000" ...

**Comment by jerrycyip** [comment]
Don't we need to change this to some form of human readable time? Unix epoch time etc (seconds since 1/1/1970) isn't going to work for users.

**Comment by anna-kartynnik** [comment]
It will be human readable for users because they will use [this modal dialog](https://xd.adobe.com/view/ca32af76-bb04-4e66-b0f4-0ddbb6525ea5-9f61/screen/cba2899e-4a58-49de-9419-05047d0671a8/)
<img width="745" alt="Screen Shot 2021-06-29 at 7 11 33 PM" src="https://user-images.githubusercontent.com/15210801/123891494-d964db80-d90d-11eb-953d-127a543652da.png">
where they choose the date from the calendar component. But internally it can be passed to the server as timestamp.
